### ISSUE TITLE
CAOS SU

### ISSUE THREAD

**Issue by JonnyTech** [eremitein/treble-patches#10]
Can you confirm method to get root / superuser in CAOS - not Magisk.
- restore stock boot image and flash CAOS
- obtain corresponding phh AOSP image
- extract and copy from AOSP to CAOS
```
/system/app/me.phh.superuser/
/system/bin/phh-su
/system/etc/init/su.rc
/system/bin/su
```
- link `/system/xbin/su` to `/system/bin/su`
- set file permissions and owners

Not sure what I am missing - unable to get superuser at all.

**Comment by eremitein** [comment]
https://forum.xda-developers.com/project-treble/trebleenabled-device-development/phh-treble-root-phhs-superuser-phhusson-t3811563/amp/

i using this

**Comment by JonnyTech** [comment]
Thank you - that showed me that my process was correct - but I forgot to set the security context of the files - d'oh!
