### ISSUE TITLE
I don't know which version to install on my Moto e5 

### ISSUE THREAD

**Issue by djgerman10** [eremitein/treble-patches#11]
[https://sourceforge.net/projects/treblerom/files/CAOS/2020.07.08/](https://sourceforge.net/projects/treblerom/files/CAOS/2020.07.08/)

Preferably I want the most optimized one, because I also want to put  on a moto e5 play

*_Greetings from Argentina, unfortunately I can not buy a better cell phone. Thanks to these wonderful works I can improve the performance of these low-end cell phones_
Sorry about my English.

**Comment by eremitein** [comment]
there is telegram channel for support https://t.me/joinchat/CdHnpVThoZCgvPZx7ESNBA

**Comment by djgerman10** [comment]
I went in but they took me out, I guess there was some captcha and I didn't read it
