### ISSUE TITLE
critical memory card problem

### ISSUE THREAD

**Issue by Maxym4uk** [eremitein/treble-patches#16]
Meizu m2 mini, MTK 6735, ARM64 A, VENDOR 9 ANDROID
Installed firmware - CAOS 11.0 v300.j
Sometimes, when you insert a memory card, it reports a problem (the memory card itself works fine) and offers to solve the problem.  But when I click to solve the problem, all the data is erased from the memory card.

After that, it will not be possible to use the memory card on your firmware (

**Comment by eremitein** [comment]
Well, check in AOSP v300j

**Comment by Maxym4uk** [comment]
> Ну, перевірте AOSP v300j

Well, on Aosp everything is fine

**Comment by Maxym4uk** [comment]
> Що ж, перевірте AOSP v300j

So you will fix?

**Comment by eremitein** [comment]
i haven't that issue, on my device sd-card works fine (vfat fs)
![photo_2020-12-17_11-39-48](https://user-images.githubusercontent.com/12787224/102452713-a2f3fd00-405c-11eb-938e-feca0fc23dda.jpg)
