### ISSUE TITLE
What agZ bgZ avZ bvZ and lite mean?

### ISSUE THREAD

**Issue by ivysrono** [eremitein/treble-patches#20]

**Comment by JonnyTech** [comment]
https://t.me/c/1424073104/78163

```
Information about what type of GSI it is

<ARCH>_xyZ

<ARCH> can either be arm, a64 or arm64
x can either be a or b
y can either be v, o, g or f
Z can be N or S

b = a/b
a = a-only

g = gapps
o = gapps-go
v = vanilla (no gapps included)
f = floss (free & open source apps instead gapps)

N = no superuser
S = superuser included

so in most common example "arm64_avN" is ARM64 A-only vanilla with no superuser
```

`Z` is **dynamic superuser** - root can be enabled/disabled during use.
`lite` means /system is **read/write** (not compressed so much bigger size)

**Comment by ivysrono** [comment]
Thank you very much.

**Comment by JonnyTech** [comment]
You're welcome. More info and support in the Telegram channel: https://t.me/joinchat/CdHnpVThoZCgvPZx7ESNBA

**Comment by ivysrono** [comment]
@JonnyTech What `o` means from 2021.02.19R?

**Comment by ivysrono** [comment]
Why Phh's `lite` is so much bigger size while `caos`'s and `havoc`'s `lite` are same or even smaller than normal?

**Comment by ivysrono** [comment]
> `lite` means /system is **read/write** (not compressed so much bigger size)

Why Phh's `lite` is so much bigger size while `caos`'s and `havoc`'s `lite` are same or even smaller than normal?
@JonnyTech @eremitein

**Comment by inneffablee** [comment]
And what does "slim" mean?
example
crDroid-8.9-arm64_bgN-slim-Unofficial.img.xz

**Comment by lepixalk** [comment]
> As for the term "slim", it usually refers to a variant of the ROM that has been stripped down to reduce its size by removing certain features or pre-installed applications. This can be useful for users who want a more lightweight ROM to save storage space or for devices with limited resources. A "slim" version of a ROM typically retains essential functionality while minimizing the footprint of the ROM. Again, the specific features and apps that are removed in a "slim" version would depend on the ROM maintainer's choices.

**Comment by Nightfigh8** [comment]
Its mainly because of gapps you can check it out and im pretty sure its like a lighter version of gapps since there is a vanilla version of the rom with no gapps and with gapps-slim is not the same as vanilla but alot less then with out the -slim so just gapps.

You could get vanilla and then customize the amount of "bloatware" you want in the orignial gapps site. and chose pico for like BARE minium funcinality but they say that but it honastly doesnt matter. in my opinion. 

-ps my english is great.

**Comment by HKMGER** [comment]
And for example A64 which means I'm looking for a rom for my cell phone and the required image is system-arm32_binder64-ab.img
