### ISSUE TITLE
Galaxy A7 2018 saftynet bypass

### ISSUE THREAD

**Issue by marko5688** [eremitein/treble-patches#24]
So when i want to pass saftynet and i install modul magisk hide porps but when i type props in terminal it say file not found, do anyone have fix?

**Comment by eremitein** [comment]
su
/data/adb/modules/MagiskHidePropsConf/system/xbin/props

**Comment by marko5688** [comment]
Thanks its working now, one more question how can i enable all cameras to work bcs for now only one back and one front works

**Comment by eremitein** [comment]
absolutely haven't ideas

but well, try enable AUX camera in the Phh settings

**Comment by marko5688** [comment]
I try this but nothing happened also i enabled in phh samsung setting access to all cameras and still nothing happens
