### ISSUE TITLE
System Setting Force Close

### ISSUE THREAD

**Issue by LongineCo** [eremitein/treble-patches#29]
It happened on both AOSP Extended V7.3 and PixysOS V3.13 roms with bless-v300m-210225-arm64-bgZ-lite.img. Zuk Z2121.
![Screenshot_20210308-071532_Blissify_Launcher 1](https://user-images.githubusercontent.com/80259256/110320552-717f4200-804b-11eb-929c-f9120484ed7f.png)

**Comment by eremitein** [comment]
> It happened on both AOSP Extended V7.3 and PixysOS V3.13 roms with bless-v300m-210225-arm64-bgZ-lite.img. Zuk Z2121

i won't help with custom vendors
on my device with stock vendor no that problem

**Comment by LongineCo** [comment]
Thanks for the quick reply and support. It has no problem on BlissRom v14.
