### ISSUE TITLE
Treble app still unloading within an hour. Toggling Airplane mode brings it back. Moto E6 T-Mobile

### ISSUE THREAD

**Issue by scottyrick** [eremitein/treble-patches#31]
On the 3/25 Rom, unloading of treble app occurs within an hour on Moto E6 on T-Mobile network. A quick Airplane Mode toggle is needed to fully load and activate it after reboot, and toggling it after it unloads, loads it right back. Hope this helps. 

On Startup:
Preferred Network Type: GSM/WCDMA/LTE
APN: PHH IMS
from "Phone Information" menu: IMS Registered

**Comment by eremitein** [comment]
> On the 3/25 Rom, unloading of treble app occurs within an hour on Moto E6

easy fix: set to the PhhTrebleApp do not Optimize Battery (Android Settings > All apps > Target app > Battery menu)
*will be in the next update

**Comment by scottyrick** [comment]
Thank you. I made the change. Glad you will put into the next update.
