### ISSUE TITLE
`Invalid sparse file format at header magic` Error

### ISSUE THREAD

**Issue by banx** [eremitein/treble-patches#32]
When I try to flash the `lir-v302-210318-arm-avZ.img` Image to the system partition, I get the error mentioned in the title.
When the flashing is complete, the device goes into a boot loop.
Is it a problem with my device or is it a problem in the way the Image file was built?

Note, flashing LOS 17.1 didn't have this problem.

**Comment by JonnyTech** [comment]
What device?

**Comment by banx** [comment]
Lenovo E10

**Comment by banx** [comment]
Can you help me understand what's the difference between `aoZ`, `agZ` and `avZ` images?

**Comment by JonnyTech** [comment]
From the Telegram group (https://t.me/joinchat/CdHnpVThoZCgvPZx7ESNBA):

```
Information about what type of GSI it is

<ARCH>_xyZ{-lite}

<ARCH> can either be arm, a64 or arm64
x can either be a or b
y can either be v, o, g or f
Z can be N, S or Z

b = a/b
a = a-only

g = gapps
o = gapps-go
v = vanilla (no gapps included)
f = floss (free & open source apps instead gapps)

N = no superuser
S = superuser included
Z = enhanced dynamic superuzer

-lite = Android11 for vndklite vendors

so in most common example "arm64_bvN" is ARM64 A/B vanilla with no superuser
```

**Comment by banx** [comment]
Is [sas-creator](https://github.com/phhusson/sas-creator) used to generate the A-only images here?
I couldn't help noticing the final line in [Andy's repo README](https://github.com/AndyCGYan/treble_build_los), which makes me wonder if this could be the cause. I've also tried Andy's images, and they generated the same error.

**Comment by JonnyTech** [comment]
Yes, system-as-system creator is used in all Android 11 builds: https://github.com/phhusson/treble_experimentations/blob/master/build.sh

**Comment by eremitein** [comment]
> When I try to flash the `lir-v302-210318-arm-avZ.img` Image to the system partition, I get the error mentioned in the title.

this is just notice, not error. anyway you can safely ignore it

> When the flashing is complete, the device goes into a boot loop
> Note, flashing LOS 17.1 didn't have this problem

first check with AOSP by phhusson, if same problem - send him bugreport
(but first you need to be sure there is no Magisk in boot partition)

**Comment by banx** [comment]
The same problem persists with AOSP by @phhusson. I'll raise this issue there.

> (but first you need to be sure there is no Magisk in boot partition)

No Magisk, the original boot partition is used.

**Comment by Nothing-Dev** [comment]
That warning is normal, your bootlop is caused by another thing. I recently flashed LiR throught fastboot, get the same warning and nothing happened, the GSI booted without issue.

**Comment by banx** [comment]
> That warning is normal, your bootlop is caused by another thing. I recently flashed LiR throught fastboot, get the same warning and nothing happened, the GSI booted without issue.

@Nothing-Dev Do you have any suggestion that may help investigating the cause of the bootloop?

**Comment by Nothing-Dev** [comment]
Did you try to use permissiver file?

**Comment by eremitein** [comment]
> > That warning is normal, your bootlop is caused by another thing. I recently flashed LiR throught fastboot, get the same warning and nothing happened, the GSI booted without issue.
> 
> @Nothing-Dev Do you have any suggestion that may help investigating the cause of the bootloop?

logs may help. also you sure you need A-only? check with [Treble Info](https://play.google.com/store/apps/details?id=tk.hack5.treblecheck) app

**Comment by Bbolaji33** [comment]
How can I tell if magisk is in boot

**Comment by Bbolaji33** [comment]
Cuz I tried lineage 17 os on a tecno pouvoir 2 pro...it got stuck in boot image...even when I format data...to unlock encryption...no is won't be found.....wat can I do
