### ISSUE TITLE
PIP mode and multitasking

### ISSUE THREAD

**Issue by thib6622** [eremitein/treble-patches#33]
hello, the picture and picture mod and the multitasking mode doesn't work with all of the roms.

**Comment by eremitein** [comment]
> hello, the picture and picture mod and the multitasking mode doesn't work with all of the roms.

these features can't work if:
a. "lowram device" trigger enabled
b. Go Gapps (aoZ,boZ) builds used

**Comment by thib6622** [comment]
thankssssss
