### ISSUE TITLE
Question: How to restore Google backups? 

### ISSUE THREAD

**Issue by GoedendagMC** [eremitein/treble-patches#42]
I have the Go version of the CAOSP11 ROM, how should I restore the Google backup to for example have my wifi passwords back?

**Comment by eremitein** [comment]
> I have the Go version of the CAOSP11 ROM, how should I restore the Google backup to for example have my wifi passwords back?

there is custom Google Cloud restore option (Settings > Accounts)

**Comment by GoedendagMC** [comment]
Thank you, is it possible that the WiFi restore is not working? Any way I could do this manually?

**Comment by eremitein** [comment]
> Thank you, is it possible that the WiFi restore is not working? Any way I could do this manually?

i don't know, i don't use Google apps and account

**Comment by GoedendagMC** [comment]
This should be done by using the wpa_suppliment.conf file. Googling will be your friend.
