### ISSUE TITLE
Request: Include Bromite Webview

### ISSUE THREAD

**Issue by JonnyTech** [eremitein/treble-patches#5]
Thank you for creating these images. Since you included the signature patch in CAOS (`Update (2020.02.27) - built with signature spoofing patch`), it is now my daily driver.

Can I request that you replace the built-in webview with Bromite (https://github.com/bromite/bromite) for those of us with privacy concerns that do not want anything Google on our devices?

Just replace `/system/product/app/webview/webview.apk` with the appropriate `xxx_SystemWebView.apk` from the Bromite repository. The end user should notice no difference at all.

**Comment by JonnyTech** [comment]
> The end user should notice no difference at all.

Scratch that - it breaks SafetyNet :/

**Comment by eremitein** [comment]
> > The end user should notice no difference at all.
> 
> Scratch that - it breaks SafetyNet :/

hi, why you think so? 
i tested today, all worked well

![photo_2020-05-01_22-44-06](https://user-images.githubusercontent.com/12787224/80827425-5fe43700-8bfd-11ea-9991-f07fb2b86df7.jpg)
![photo_2020-05-01_22-44-02](https://user-images.githubusercontent.com/12787224/80827427-61156400-8bfd-11ea-929f-f8e30791fdde.jpg)
![photo_2020-05-01_22-43-58](https://user-images.githubusercontent.com/12787224/80827429-61adfa80-8bfd-11ea-9a23-4a17acff5db2.jpg)
![photo_2020-05-01_22-43-54](https://user-images.githubusercontent.com/12787224/80827431-62df2780-8bfd-11ea-93eb-8d45e8f54e65.jpg)

**Comment by JonnyTech** [comment]
It states it in the wiki: https://github.com/bromite/bromite/wiki/Installing-SystemWebView#installation-options

But I do not have a need nor do I use safetynet so could not check.

**Comment by eremitein** [comment]
Oh, its' hacks way to install:)
and the information is old

> It states it in the wiki: https://github.com/bromite/bromite/wiki/Installing-SystemWebView#installation-options
> 
> But I do not have a need nor do I use safetynet so could not check.

**Comment by JonnyTech** [comment]
Ah, so does that mean that you will include it? I have used it for ages on many phones and ROMs without issue. The less big-brother can "phone home", the better.

**Comment by eremitein** [comment]
yes probably, in LOSQ already included
