### ISSUE TITLE
Camera crashes and not working on crDRom11 arm64 A-only

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [eremitein/treble-patches#50]
I have Honor 6X  (Hi6250) and found out that the camera not matter what app I use is not working despite being worked in another GSI. Any flashable zip to fix it?

**Comment by MohammedMehdiTBER** [comment]
It is working now after I flashed another kernel and made SELinux Permissive

**Comment by xc112lg** [comment]
sir where is your latest github repo for crdrom11, i want to rebuild the rom to pass saferynet
