### ISSUE TITLE
BLESS-GApps

### ISSUE THREAD

**Issue by leonidofsparta** [eremitein/treble-patches#9]
Hello. I have an Alcatel 1S (5024D), and there is no custom recovery for it. I can't place all the needed files in the system partition because in this ROM it's too small. I wanted to ask you if you could make a gapps version of the rom. Thank you very much in advance, you would help me a lot, I love your rom.

**Comment by eremitein** [comment]
hi, i can't promise

**Comment by leonidofsparta** [comment]
Hi, thanks for replying. I tried to include all the apks and frameworks in the unpacked system, but I can't find a way to pack it back. If you told me how to do just this I could test it and eventually send it to you so that you can share it with the other users

**Comment by eremitein** [comment]
depends on how you unpack/modify it. there is a lot information on XDA, you can search there. and if you want you can join to my telegram group, link on the Treble GSI List page

**Comment by philalat** [comment]
good morning 
i download your last BLESS rom but:
- i can't install gapps micro?
 - and i tried call BT but it's do no works.

**Comment by philalat** [comment]
Hi
i love the boot moving image very sweet! i try to download another gapps= nano and i will see.
for call BT do you have an idea.
best regards

**Comment by eremitein** [comment]
hello

1. before install gapps do automatic system resize in twrp
2. try workaround in Phh settings, search something like audio policy or bluetooth fix

**Comment by philalat** [comment]
Hi
1 i do that in twrp but i always have error 70.
2  in phh setting/setting i open Misc feature /bluetooth workaround and i choice Mediatek.
whatelse :)

**Comment by philalat** [comment]
good morning, afternoon or evening according to your location
i downloaded the last version of your rom (v220)
forgapps it's good with nano version, but for sound call BT always nothing. I have sound for music player or movies but nothing foe calls.
do you have an idea
best regards

**Comment by eremitein** [comment]
hi
is a known problem with BT calls in all Q GSI, read project page
you can take logs and send there https://github.com/phhusson/treble_experimentations/issues

**Comment by philalat** [comment]
Hi Victor
Thank you for your answer. I read about call BT problem, but in the
presentation of BLESS ROM it's written that call BT were fixed.
Good night

**Comment by eremitein** [comment]
oh, this is just fix for regression in 2020.06.05 build.
i forget add generic bug section. project page will be updated, sorry

> but in the presentation of BLESS ROM it's written that call BT were fixed

**Comment by philalat** [comment]
hi victor
could you give me your location to avoid waking up? for the BT problem
could you say me on the root stock system where i'll can see the folder
which have the BT?
because on my stock's rom the BT worked, so as a beginner i think if i can
compare the both, I'll find the missing files.
But you already thought about this.
best regards

**Comment by eremitein** [comment]
i don't know exactly
you can look at system/etc/bluetooth
but i guess deal not in config, but in stock binary blobs

**Comment by philalat** [comment]
Hi victor
could you say me what name of text editor i could use on my PC to open root system folder?
because i tried with note pad but the folder is too big for it.
thanks

**Comment by eremitein** [comment]
i can't understand you. why you want open root system folder in text editor?..

**Comment by philalat** [comment]
To see if it's possible the differences between original ROM and
yours.finally see what's the making folder.

**Comment by philalat** [comment]
But I haven't your knowledge about this. I want to understand what's don't
work that all.I'm curious.

Le lun. 22 juin 2020 à 18:21, Philippe Granet <pgranet17@gmail.com> a
écrit :

**Comment by andrey167** [comment]
Hi, I have the same problem.my device can't have twrp support due to stock android 10, and the problem with gaps is very critical for me.I would like to have gapps already present in these builds

**Comment by Cyberavater** [comment]
I'd appreciate it too if you could add a GAPPS version, Thanks for your work!

**Comment by Cyberavater** [comment]
>before install gapps do automatic system resize in twrp

@eremitein By the way, How to do automatic system resize in twrp you mentioned?
